### ISSUE TITLE
HEM Refresh Rates

### ISSUE THREAD

**Issue by crosbymichael** [codahq/hubitat_codahq#3]
I'm having issues with the gen5 driver for the HEM.  The referesh rates for the power, voltage, and current are very slow and i'm unsure how to speed things up to a 1-5sec tick interval.

I'll see if i can fix it in the code if there isn't any configuration options in the gui.

Anything helps, else i'll keep looking and poking around with the code

**Comment by codahq** [comment]
First off, I said specifically I am not supporting this driver.  Second, you really don't want to speed up reports to 1 to 5 seconds.  Third, it's documented in the device's user manual.  And fourth, it's supported by the preferences in the driver.
